import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Provider as CartProvider } from "@/context/CartProvider";
import Cart from "@/components/cart/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={`antialiased`}>
          <Cart />
          <Header />
          <main className="flex max-w-[1400px] px-6 mx-auto flex-col items-center justify-between">
            {children}
          </main>
          <Footer />
        </body>
      </CartProvider>
    </html>
  );
}
